#!/bin/bash
# Glass Dagger: Capture IR Artifacts
# Generates readable LLVM IR at each pipeline stage

set -e

echo "=== Capturing IR Artifacts ==="
echo ""

# Ensure environment is loaded
if [ -z "$ENZYME_PLUGIN" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "$SCRIPT_DIR/toolchain/env.sh"
fi

mkdir -p artifacts/ir
cd build

echo "Generating IR artifacts for M2 pendulum..."

# Stage 1: Original IR (before Enzyme)
if [ -f pendulum_opt.ll ]; then
    cp pendulum_opt.ll ../artifacts/ir/loss_original.ll
    echo "✅ Captured: loss_original.ll"
fi

# Stage 2: After Enzyme AD pass
if [ -f pendulum_opt_enzyme.ll ]; then
    cp pendulum_opt_enzyme.ll ../artifacts/ir/loss_enzyme.ll
    echo "✅ Captured: loss_enzyme.ll (with gradients)"
fi

# Stage 3: After LLVM optimization
if [ -f pendulum_opt_opt.ll ]; then
    cp pendulum_opt_opt.ll ../artifacts/ir/loss_optimized.ll
    echo "✅ Captured: loss_optimized.ll (final)"
fi

cd ..

# Create README for IR artifacts
cat > artifacts/ir/README.md <<'EOF'
# LLVM IR Artifacts

This directory contains the LLVM IR at each stage of the compilation pipeline, demonstrating how Enzyme generates and LLVM optimizes gradient code.

## Pipeline Stages

### 1. `loss_original.ll` - Original IR
Generated by: `clang -S -emit-llvm -O2 pendulum_opt.c`

This is the LLVM IR before Enzyme's AD pass. The `loss_omega1` function contains:
- Inlined RK4 integration loop (1000 iterations)
- Double pendulum physics equations
- Loss computation

**Key**: No gradient code yet - just the forward pass.

### 2. `loss_enzyme.ll` - After Enzyme AD
Generated by: `opt --load-pass-plugin=LLVMEnzyme.so -passes=enzyme`

Enzyme has generated the adjoint (gradient) code. Look for:
- `diffe_loss_omega1` - the gradient function
- Reverse-mode AD through the entire RK4 loop
- Adjoint variables for each intermediate computation

**Key**: This is the "raw" gradient code before optimization.

### 3. `loss_optimized.ll` - After LLVM -O2
Generated by: `opt -O2`

LLVM's optimizer has simplified and optimized the gradient code:
- Dead code elimination
- Common subexpression elimination
- Loop optimizations
- Instruction scheduling

**Key**: This is the final gradient code that gets compiled to machine code.

## Viewing the IR

```bash
# View original function
grep -A 50 "define.*loss_omega1" loss_original.ll

# View generated gradient
grep -A 100 "define.*diffe.*loss_omega1" loss_enzyme.ll

# Compare sizes
wc -l *.ll
```

## What to Look For

1. **Function signature changes**: Enzyme adds gradient output parameters
2. **Adjoint variables**: Variables prefixed with `_d` or `adjoint`
3. **Reverse loop**: The RK4 loop is traversed backwards for backpropagation
4. **Optimization impact**: Compare `loss_enzyme.ll` vs `loss_optimized.ll` size

## Technical Notes

- All IR is in text format (`.ll` with `-S` flag, not bitcode `.bc`)
- Enzyme operates at the LLVM IR level, not source level
- The gradient code is generated once at compile-time, not runtime
EOF

echo ""
echo "✅ IR artifacts captured in artifacts/ir/"
echo "   - loss_original.ll"
echo "   - loss_enzyme.ll"
echo "   - loss_optimized.ll"
echo "   - README.md"
